##########################################################################
# Copyright 2007 Applied Research in Patacriticism and the University of Virginia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##########################################################################

class Search < ActiveRecord::Base
  belongs_to :user
  has_many :constraints, :dependent => :destroy


  def self.role_field_names
    {
      'role_ARC' => {:display=>"Architect", :search_field=>"search_role_ARC"},
      'role_ART' => {:display=>"Artist", :search_field=>"search_artist"},
      'role_AUT' => {:display=>"Author", :search_field=>"ath"},
      'role_BKD' => {:display=>"Book Designer", :search_field=>"search_role_BKD"},
      'role_BKP' => {:display=>"Book Producer", :search_field=>"search_role_BKP"},
      'role_BND' => {:display=>"Binder", :search_field=>"search_role_BND"},
      'role_CLL' => {:display=>"Calligrapher", :search_field=>"search_role_CLL"},
      'role_CLR' => {:display=>"Colorist", :search_field=>"search_role_CLR"},
      'role_CMT' => {:display=>"Compositor", :search_field=>"search_role_CMT"},
      'role_COL' => {:display=>"Collector", :search_field=>"search_role_COL"},
      'role_COM' => {:display=>"Compiler", :search_field=>"search_role_COM"},
      'role_CRE' => {:display=>"Creator", :search_field=>"search_role_CRE"},
      'role_CTG' => {:display=>"Cartographer", :search_field=>"search_role_CTG"},
      'role_CWT' => {:display=>"Commentator", :search_field=>"search_role_CWT"},
      'role_DUB' => {:display=>"Dubious Author", :search_field=>"search_role_DUB"},
      'role_EDT' => {:display=>"Editor", :search_field=>"ed"},
      'role_FAC' => {:display=>"Facsimilist", :search_field=>"search_role_FAC"},
      'role_ILL' => {:display=>"Illustrator", :search_field=>"search_role_ILL"},
      'role_ILU' => {:display=>"Illuminator", :search_field=>"search_role_ILU"},
      'role_LTG' => {:display=>"Lithographer", :search_field=>"search_role_LTG"},
      'role_OWN' => {:display=>"Owner", :search_field=>"search_owner"},
      'role_PBL' => {:display=>"Publisher", :search_field=>"pub"},
      'role_POP' => {:display=>"Printer of plates", :search_field=>"search_role_POP"},
      'role_PRM' => {:display=>"Printmaker", :search_field=>"search_role_PRM"},
      'role_PRT' => {:display=>"Printer", :search_field=>"search_role_PRT"},
      'role_RBR' => {:display=>"Rubricator", :search_field=>"search_role_RBR"},
      'role_RPS' => {:display=>"Repository", :search_field=>"search_role_RPS"},
      'role_SCL' => {:display=>"Sculptor", :search_field=>"search_role_SCL"},
      'role_SCR' => {:display=>"Scribe", :search_field=>"search_role_SCR"},
      'role_TRL' => {:display=>"Translator", :search_field=>"search_role_TRL"},
      'role_TYD' => {:display=>"Type Designer", :search_field=>"search_role_TYD"},
      'role_TYG' => {:display=>"Typographer", :search_field=>"search_role_TYG"},
      'role_WDC' => {:display=>"Wood Cutter", :search_field=>"search_role_WDC"},
      'role_WDE' => {:display=>"Wood Engraver", :search_field=>"search_role_WDE"},
      'role_ABR' => {:display=>"Abridger", :search_field=>"search_role_ABR"},
      'role_ACP' => {:display=>"Art copyist", :search_field=>"search_role_ACP"},
      'role_ACT' => {:display=>"Actor", :search_field=>"search_role_ACT"},
      'role_ADI' => {:display=>"Art director", :search_field=>"search_role_ADI"},
      'role_ADP' => {:display=>"Adapter", :search_field=>"search_role_ADP"},
      'role_AFT' => {:display=>"Author of afterword, colophon, etc.", :search_field=>"search_role_AFT"},
      'role_ANL' => {:display=>"Analyst", :search_field=>"search_role_ANL"},
      'role_ANM' => {:display=>"Animator", :search_field=>"search_role_ANM"},
      'role_ANN' => {:display=>"Annotator", :search_field=>"search_role_ANN"},
      'role_ANT' => {:display=>"Bibliographic antecedent", :search_field=>"search_role_ANT"},
      'role_APE' => {:display=>"Appellee", :search_field=>"search_role_APE"},
      'role_APL' => {:display=>"Appellant", :search_field=>"search_role_APL"},
      'role_APP' => {:display=>"Applicant", :search_field=>"search_role_APP"},
      'role_AQT' => {:display=>"Author in quotations or text abstracts", :search_field=>"search_role_AQT"},
      'role_ARD' => {:display=>"Artistic director", :search_field=>"search_role_ARD"},
      'role_ARR' => {:display=>"Arranger", :search_field=>"search_role_ARR"},
      'role_ASG' => {:display=>"Assignee", :search_field=>"search_role_ASG"},
      'role_ASN' => {:display=>"Associated name", :search_field=>"search_role_ASN"},
      'role_ATO' => {:display=>"Autographer", :search_field=>"search_role_ATO"},
      'role_ATT' => {:display=>"Attributed name", :search_field=>"search_role_ATT"},
      'role_AUC' => {:display=>"Auctioneer", :search_field=>"search_role_AUC"},
      'role_AUD' => {:display=>"Author of dialog", :search_field=>"search_role_AUD"},
      'role_AUI' => {:display=>"Author of introduction, etc.", :search_field=>"search_role_AUI"},
      'role_AUS' => {:display=>"Screenwriter", :search_field=>"search_role_AUS"},
      'role_BDD' => {:display=>"Binding designer", :search_field=>"search_role_BDD"},
      'role_BJD' => {:display=>"Bookjacket designer", :search_field=>"search_role_BJD"},
      'role_BLW' => {:display=>"Blurb writer", :search_field=>"search_role_BLW"},
      'role_BPD' => {:display=>"Bookplate designer", :search_field=>"search_role_BPD"},
      'role_BRD' => {:display=>"Broadcaster", :search_field=>"search_role_BRD"},
      'role_BRL' => {:display=>"Braille embosser", :search_field=>"search_role_BRL"},
      'role_BSL' => {:display=>"Bookseller", :search_field=>"search_role_BSL"},
      'role_CAS' => {:display=>"Caster", :search_field=>"search_role_CAS"},
      'role_CCP' => {:display=>"Conceptor", :search_field=>"search_role_CCP"},
      'role_CHR' => {:display=>"Choreographer", :search_field=>"search_role_CHR"},
      'role_CLI' => {:display=>"Client", :search_field=>"search_role_CLI"},
      'role_CLT' => {:display=>"Collotyper", :search_field=>"search_role_CLT"},
      'role_CMM' => {:display=>"Commentator", :search_field=>"search_role_CMM"},
      'role_CMP' => {:display=>"Composer", :search_field=>"search_role_CMP"},
      'role_CND' => {:display=>"Conductor", :search_field=>"search_role_CND"},
      'role_CNG' => {:display=>"Cinematographer", :search_field=>"search_role_CNG"},
      'role_CNS' => {:display=>"Censor", :search_field=>"search_role_CNS"},
      'role_COE' => {:display=>"Contestant-appellee", :search_field=>"search_role_COE"},
      'role_CON' => {:display=>"Conservator", :search_field=>"search_role_CON"},
      'role_COR' => {:display=>"Collection registrar", :search_field=>"search_role_COR"},
      'role_COS' => {:display=>"Contestant", :search_field=>"search_role_COS"},
      'role_COT' => {:display=>"Contestant-appellant", :search_field=>"search_role_COT"},
      'role_COU' => {:display=>"Court governed", :search_field=>"search_role_COU"},
      'role_COV' => {:display=>"Cover designer", :search_field=>"search_role_COV"},
      'role_CPC' => {:display=>"Copyright claimant", :search_field=>"search_role_CPC"},
      'role_CPE' => {:display=>"Complainant-appellee", :search_field=>"search_role_CPE"},
      'role_CPH' => {:display=>"Copyright holder", :search_field=>"search_role_CPH"},
      'role_CPL' => {:display=>"Complainant", :search_field=>"search_role_CPL"},
      'role_CPT' => {:display=>"Complainant-appellant", :search_field=>"search_role_CPT"},
      'role_CRP' => {:display=>"Correspondent", :search_field=>"search_role_CRP"},
      'role_CRR' => {:display=>"Corrector", :search_field=>"search_role_CRR"},
      'role_CRT' => {:display=>"Court reporter", :search_field=>"search_role_CRT"},
      'role_CSL' => {:display=>"Consultant", :search_field=>"search_role_CSL"},
      'role_CSP' => {:display=>"Consultant to a project", :search_field=>"search_role_CSP"},
      'role_CST' => {:display=>"Costume designer", :search_field=>"search_role_CST"},
      'role_CTB' => {:display=>"Contributor", :search_field=>"search_role_CTB"},
      'role_CTE' => {:display=>"Contestee-appellee", :search_field=>"search_role_CTE"},
      'role_CTR' => {:display=>"Contractor", :search_field=>"search_role_CTR"},
      'role_CTS' => {:display=>"Contestee", :search_field=>"search_role_CTS"},
      'role_CTT' => {:display=>"Contestee-appellant", :search_field=>"search_role_CTT"},
      'role_CUR' => {:display=>"Curator", :search_field=>"search_role_CUR"},
      'role_DBP' => {:display=>"Distribution place", :search_field=>"search_role_DBP"},
      'role_DFD' => {:display=>"Defendant", :search_field=>"search_role_DFD"},
      'role_DFE' => {:display=>"Defendant-appellee", :search_field=>"search_role_DFE"},
      'role_DFT' => {:display=>"Defendant-appellant", :search_field=>"search_role_DFT"},
      'role_DGG' => {:display=>"Degree granting institution", :search_field=>"search_role_DGG"},
      'role_DGS' => {:display=>"Degree supervisor", :search_field=>"search_role_DGS"},
      'role_DIS' => {:display=>"Dissertant", :search_field=>"search_role_DIS"},
      'role_DLN' => {:display=>"Delineator", :search_field=>"search_role_DLN"},
      'role_DNC' => {:display=>"Dancer", :search_field=>"search_role_DNC"},
      'role_DNR' => {:display=>"Donor", :search_field=>"search_role_DNR"},
      'role_DPC' => {:display=>"Depicted", :search_field=>"search_role_DPC"},
      'role_DPT' => {:display=>"Depositor", :search_field=>"search_role_DPT"},
      'role_DRM' => {:display=>"Draftsman", :search_field=>"search_role_DRM"},
      'role_DRT' => {:display=>"Director", :search_field=>"search_role_DRT"},
      'role_DSR' => {:display=>"Designer", :search_field=>"search_role_DSR"},
      'role_DST' => {:display=>"Distributor", :search_field=>"search_role_DST"},
      'role_DTC' => {:display=>"Data contributor", :search_field=>"search_role_DTC"},
      'role_DTE' => {:display=>"Dedicatee", :search_field=>"search_role_DTE"},
      'role_DTM' => {:display=>"Data manager", :search_field=>"search_role_DTM"},
      'role_DTO' => {:display=>"Dedicator", :search_field=>"search_role_DTO"},
      'role_EDC' => {:display=>"Editor of compilation", :search_field=>"search_role_EDC"},
      'role_EDM' => {:display=>"Editor of moving image work", :search_field=>"search_role_EDM"},
      'role_EGR' => {:display=>"Engraver", :search_field=>"search_role_EGR"},
      'role_ELG' => {:display=>"Electrician", :search_field=>"search_role_ELG"},
      'role_ELT' => {:display=>"Electrotyper", :search_field=>"search_role_ELT"},
      'role_ENG' => {:display=>"Engineer", :search_field=>"search_role_ENG"},
      'role_ENJ' => {:display=>"Enacting jurisdiction", :search_field=>"search_role_ENJ"},
      'role_ETR' => {:display=>"Etcher", :search_field=>"search_role_ETR"},
      'role_EVP' => {:display=>"Event place", :search_field=>"search_role_EVP"},
      'role_EXP' => {:display=>"Expert", :search_field=>"search_role_EXP"},
      'role_FDS' => {:display=>"Film distributor", :search_field=>"search_role_FDS"},
      'role_FLD' => {:display=>"Field director", :search_field=>"search_role_FLD"},
      'role_FLM' => {:display=>"Film editor", :search_field=>"search_role_FLM"},
      'role_FMD' => {:display=>"Film director", :search_field=>"search_role_FMD"},
      'role_FMK' => {:display=>"Filmmaker", :search_field=>"search_role_FMK"},
      'role_FMO' => {:display=>"Former owner", :search_field=>"search_role_FMO"},
      'role_FMP' => {:display=>"Film producer", :search_field=>"search_role_FMP"},
      'role_FND' => {:display=>"Funder", :search_field=>"search_role_FND"},
      'role_FPY' => {:display=>"First party", :search_field=>"search_role_FPY"},
      'role_FRG' => {:display=>"Forger", :search_field=>"search_role_FRG"},
      'role_GIS' => {:display=>"Geographic information specialist", :search_field=>"search_role_GIS"},
      'role_HIS' => {:display=>"Host institution", :search_field=>"search_role_HIS"},
      'role_HNR' => {:display=>"Honoree", :search_field=>"search_role_HNR"},
      'role_HST' => {:display=>"Host", :search_field=>"search_role_HST"},
      'role_INS' => {:display=>"Inscriber", :search_field=>"search_role_INS"},
      'role_INV' => {:display=>"Inventor", :search_field=>"search_role_INV"},
      'role_ISB' => {:display=>"Issuing body", :search_field=>"search_role_ISB"},
      'role_ITR' => {:display=>"Instrumentalist", :search_field=>"search_role_ITR"},
      'role_IVE' => {:display=>"Interviewee", :search_field=>"search_role_IVE"},
      'role_IVR' => {:display=>"Interviewer", :search_field=>"search_role_IVR"},
      'role_JUD' => {:display=>"Judge", :search_field=>"search_role_JUD"},
      'role_JUG' => {:display=>"Jurisdiction governed", :search_field=>"search_role_JUG"},
      'role_LBR' => {:display=>"Laboratory", :search_field=>"search_role_LBR"},
      'role_LBT' => {:display=>"Librettist", :search_field=>"search_role_LBT"},
      'role_LDR' => {:display=>"Laboratory director", :search_field=>"search_role_LDR"},
      'role_LED' => {:display=>"Lead", :search_field=>"search_role_LED"},
      'role_LEE' => {:display=>"Libelee-appellee", :search_field=>"search_role_LEE"},
      'role_LEL' => {:display=>"Libelee", :search_field=>"search_role_LEL"},
      'role_LEN' => {:display=>"Lender", :search_field=>"search_role_LEN"},
      'role_LET' => {:display=>"Libelee-appellant", :search_field=>"search_role_LET"},
      'role_LGD' => {:display=>"Lighting designer", :search_field=>"search_role_LGD"},
      'role_LIE' => {:display=>"Libelant-appellee", :search_field=>"search_role_LIE"},
      'role_LIL' => {:display=>"Libelant", :search_field=>"search_role_LIL"},
      'role_LIT' => {:display=>"Libelant-appellant", :search_field=>"search_role_LIT"},
      'role_LSA' => {:display=>"Landscape architect", :search_field=>"search_role_LSA"},
      'role_LSE' => {:display=>"Licensee", :search_field=>"search_role_LSE"},
      'role_LSO' => {:display=>"Licensor", :search_field=>"search_role_LSO"},
      'role_LYR' => {:display=>"Lyricist", :search_field=>"search_role_LYR"},
      'role_MCP' => {:display=>"Music copyist", :search_field=>"search_role_MCP"},
      'role_MDC' => {:display=>"Metadata contact", :search_field=>"search_role_MDC"},
      'role_MED' => {:display=>"Medium", :search_field=>"search_role_MED"},
      'role_MFP' => {:display=>"Manufacture place", :search_field=>"search_role_MFP"},
      'role_MFR' => {:display=>"Manufacturer", :search_field=>"search_role_MFR"},
      'role_MOD' => {:display=>"Moderator", :search_field=>"search_role_MOD"},
      'role_MON' => {:display=>"Monitor", :search_field=>"search_role_MON"},
      'role_MRB' => {:display=>"Marbler", :search_field=>"search_role_MRB"},
      'role_MRK' => {:display=>"Markup editor", :search_field=>"search_role_MRK"},
      'role_MSD' => {:display=>"Musical director", :search_field=>"search_role_MSD"},
      'role_MTE' => {:display=>"Metal-engraver", :search_field=>"search_role_MTE"},
      'role_MTK' => {:display=>"Minute taker", :search_field=>"search_role_MTK"},
      'role_MUS' => {:display=>"Musician", :search_field=>"search_role_MUS"},
      'role_NRT' => {:display=>"Narrator", :search_field=>"search_role_NRT"},
      'role_OPN' => {:display=>"Opponent", :search_field=>"search_role_OPN"},
      'role_ORG' => {:display=>"Originator", :search_field=>"search_role_ORG"},
      'role_ORM' => {:display=>"Organizer", :search_field=>"search_role_ORM"},
      'role_OSP' => {:display=>"Onscreen presenter", :search_field=>"search_role_OSP"},
      'role_OTH' => {:display=>"Other", :search_field=>"search_role_OTH"},
      'role_PAN' => {:display=>"Panelist", :search_field=>"search_role_PAN"},
      'role_PAT' => {:display=>"Patron", :search_field=>"search_role_PAT"},
      'role_PBD' => {:display=>"Publishing director", :search_field=>"search_role_PBD"},
      'role_PDR' => {:display=>"Project director", :search_field=>"search_role_PDR"},
      'role_PFR' => {:display=>"Proofreader", :search_field=>"search_role_PFR"},
      'role_PHT' => {:display=>"Photographer", :search_field=>"search_role_PHT"},
      'role_PLT' => {:display=>"Platemaker", :search_field=>"search_role_PLT"},
      'role_PMA' => {:display=>"Permitting agency", :search_field=>"search_role_PMA"},
      'role_PMN' => {:display=>"Production manager", :search_field=>"search_role_PMN"},
      'role_PPM' => {:display=>"Papermaker", :search_field=>"search_role_PPM"},
      'role_PPT' => {:display=>"Puppeteer", :search_field=>"search_role_PPT"},
      'role_PRA' => {:display=>"Praeses", :search_field=>"search_role_PRA"},
      'role_PRC' => {:display=>"Process contact", :search_field=>"search_role_PRC"},
      'role_PRD' => {:display=>"Production personnel", :search_field=>"search_role_PRD"},
      'role_PRE' => {:display=>"Presenter", :search_field=>"search_role_PRE"},
      'role_PRF' => {:display=>"Performer", :search_field=>"search_role_PRF"},
      'role_PRG' => {:display=>"Programmer", :search_field=>"search_role_PRG"},
      'role_PRN' => {:display=>"Production company", :search_field=>"search_role_PRN"},
      'role_PRO' => {:display=>"Producer", :search_field=>"search_role_PRO"},
      'role_PRP' => {:display=>"Production place", :search_field=>"search_role_PRP"},
      'role_PRS' => {:display=>"Production designer", :search_field=>"search_role_PRS"},
      'role_PRV' => {:display=>"Provider", :search_field=>"search_role_PRV"},
      'role_PTA' => {:display=>"Patent applicant", :search_field=>"search_role_PTA"},
      'role_PTE' => {:display=>"Plaintiff-appellee", :search_field=>"search_role_PTE"},
      'role_PTF' => {:display=>"Plaintiff", :search_field=>"search_role_PTF"},
      'role_PTH' => {:display=>"Patent holder", :search_field=>"search_role_PTH"},
      'role_PTT' => {:display=>"Plaintiff-appellant", :search_field=>"search_role_PTT"},
      'role_PUP' => {:display=>"Publication place", :search_field=>"search_role_PUP"},
      'role_RCD' => {:display=>"Recordist", :search_field=>"search_role_RCD"},
      'role_RCE' => {:display=>"Recording engineer", :search_field=>"search_role_RCE"},
      'role_RCP' => {:display=>"Addressee", :search_field=>"search_role_RCP"},
      'role_RDD' => {:display=>"Radio director", :search_field=>"search_role_RDD"},
      'role_RED' => {:display=>"Redaktor", :search_field=>"search_role_RED"},
      'role_REN' => {:display=>"Renderer", :search_field=>"search_role_REN"},
      'role_RES' => {:display=>"Researcher", :search_field=>"search_role_RES"},
      'role_REV' => {:display=>"Reviewer", :search_field=>"search_role_REV"},
      'role_RPC' => {:display=>"Radio producer", :search_field=>"search_role_RPC"},
      'role_RPT' => {:display=>"Reporter", :search_field=>"search_role_RPT"},
      'role_RPY' => {:display=>"Responsible party", :search_field=>"search_role_RPY"},
      'role_RSE' => {:display=>"Respondent-appellee", :search_field=>"search_role_RSE"},
      'role_RSG' => {:display=>"Restager", :search_field=>"search_role_RSG"},
      'role_RSP' => {:display=>"Respondent", :search_field=>"search_role_RSP"},
      'role_RSR' => {:display=>"Restorationist", :search_field=>"search_role_RSR"},
      'role_RST' => {:display=>"Respondent-appellant", :search_field=>"search_role_RST"},
      'role_RTH' => {:display=>"Research team head", :search_field=>"search_role_RTH"},
      'role_RTM' => {:display=>"Research team member", :search_field=>"search_role_RTM"},
      'role_SAD' => {:display=>"Scientific advisor", :search_field=>"search_role_SAD"},
      'role_SCE' => {:display=>"Scenarist", :search_field=>"search_role_SCE"},
      'role_SDS' => {:display=>"Sound designer", :search_field=>"search_role_SDS"},
      'role_SEC' => {:display=>"Secretary", :search_field=>"search_role_SEC"},
      'role_SGD' => {:display=>"Stage director", :search_field=>"search_role_SGD"},
      'role_SGN' => {:display=>"Signer", :search_field=>"search_role_SGN"},
      'role_SHT' => {:display=>"Supporting host", :search_field=>"search_role_SHT"},
      'role_SLL' => {:display=>"Seller", :search_field=>"search_role_SLL"},
      'role_SNG' => {:display=>"Singer", :search_field=>"search_role_SNG"},
      'role_SPK' => {:display=>"Speaker", :search_field=>"search_role_SPK"},
      'role_SPN' => {:display=>"Sponsor", :search_field=>"search_role_SPN"},
      'role_SPY' => {:display=>"Second party", :search_field=>"search_role_SPY"},
      'role_SRV' => {:display=>"Surveyor", :search_field=>"search_role_SRV"},
      'role_STD' => {:display=>"Set designer", :search_field=>"search_role_STD"},
      'role_STG' => {:display=>"Setting", :search_field=>"search_role_STG"},
      'role_STL' => {:display=>"Storyteller", :search_field=>"search_role_STL"},
      'role_STM' => {:display=>"Stage manager", :search_field=>"search_role_STM"},
      'role_STN' => {:display=>"Standards body", :search_field=>"search_role_STN"},
      'role_STR' => {:display=>"Stereotyper", :search_field=>"search_role_STR"},
      'role_TCD' => {:display=>"Technical director", :search_field=>"search_role_TCD"},
      'role_TCH' => {:display=>"Teacher", :search_field=>"search_role_TCH"},
      'role_THS' => {:display=>"Thesis advisor", :search_field=>"search_role_THS"},
      'role_TLD' => {:display=>"Television director", :search_field=>"search_role_TLD"},
      'role_TLP' => {:display=>"Television producer", :search_field=>"search_role_TLP"},
      'role_TRC' => {:display=>"Transcriber", :search_field=>"search_role_TRC"},
      'role_UVP' => {:display=>"University place", :search_field=>"search_role_UVP"},
      'role_VAC' => {:display=>"Voice actor", :search_field=>"search_role_VAC"},
      'role_VDG' => {:display=>"Videographer", :search_field=>"search_role_VDG"},
      'role_WAC' => {:display=>"Writer of added commentary", :search_field=>"search_role_WAC"},
      'role_WAL' => {:display=>"Writer of added lyrics", :search_field=>"search_role_WAL"},
      'role_WAM' => {:display=>"Writer of accompanying material", :search_field=>"search_role_WAM"},
      'role_WAT' => {:display=>"Writer of added text", :search_field=>"search_role_WAT"},
      'role_WIN' => {:display=>"Writer of introduction", :search_field=>"search_role_WIN"},
      'role_WIT' => {:display=>"Witness", :search_field=>"search_role_WIT"},
      'role_WPR' => {:display=>"Writer of preface", :search_field=>"search_role_WPR"},
      'role_WST' => {:display=>"Writer of supplementary textual content", :search_field=>"search_role_WST"},
    }
  end


  def to_solr_expression
    clauses = []
    constraints.each do |constraint|
      clauses << constraint.to_solr_expression
    end

    "(#{clauses.join(" AND ")})"
  end

  def to_s
    s = ""
    constraints.each do |constraint|
      s << "#{constraint}\n"
    end
    s
  end
end
